#include "ResultWorkers.h"

ResultWorkers::ResultWorkers():Tool(){}


bool ResultWorkers::Initialise(std::string configfile, DataModel &data){
	
	if(configfile!="")  m_variables.Initialise(configfile);
	//m_variables.Print();
	
	m_data= &data;
	m_log= m_data->Log;
	
	if(!m_variables.Get("verbose",m_verbose)) m_verbose=1;
	
	thread_args.m_data = m_data;
	m_data->utils.CreateThread("result_job_distributor", &Thread, &thread_args);
	m_data->num_threads++;
	
	return true;
}


bool ResultWorkers::Execute(){
	
	// FIXME ok but actually this kills all our jobs, not just our job distributor
	// so we don't want to do that.
	if(!thread_args.running){
		Log(m_tool_name+" Execute found thread not running!",v_error);
		Finalise();
		Initialise(); // FIXME should we give up if Initialise returns false? should we set StopLoop to 1?
		++m_data->result_job_distributor_thread_crashes;
	}
	
	return true;
}


bool ResultWorkers::Finalise(){
	
	// signal job distributor thread to stop
	Log(m_tool_name+": Joining receiver thread",v_warning);
	m_data->utils.KillThread(&thread_args);
	Log(m_tool_name+": Finished",v_warning);
	m_data->num_threads--;
	
	return true;
}


void ResultWorkers::Thread(Thread_args* args){
	
	ResultJobDistributor_args* m_args = reinterpret_cast<ResultJobDistributor_args*>(args);
	
	// grab a batch of read queries, with results awaiting conversion
	std::unique_lock<std::mutex> locker(m_args->m_data->read_replies_mtx);
	if(!m_args->m_data->read_replies.empty()){
		std::swap(m_args->m_data->read_replies, m_args->local_msg_queue);
	}
	locker.unlock();
	
	// add a job for each batch to the queue
	for(int i=0; i<m_args->local_msg_queue.size(); ++i){
		
		// add a new Job to the job queue to process this data
		Job* the_job = job_pool.GetNew("result_worker");
		if(the_job->data == nullptr){
			// on first creation of the job, make it a JobStruct to encapsulate its data
			// N.B. Pool::GetNew will only invoke the constructor if this is a new instance,
			// (not if it's been used before and then returned to the pool)
			// so don't pass job-specific variables to the constructor
			the_job->data = job_struct_pool.GetNew(&job_struct_pool, m_args->m_data);
		} else {
			// FIXME error
			std::cerr<<"result_worker Job with non-null data pointer!"<<std::endl;
		}
		
		the_job->func = ResultJob;
		the_job->fail_func = ResultJobFail;
		
		ResultJobStruct* job_data = dynamic_cast<ResultJobStruct*>(the_job->data);
		job_data->batch = m_args->local_msg_queue[i];
		
		/*ok =*/ m_args->m_data->job_queue.AddJob(the_job); // just checks if you've defined func and first_vals = true;
		
	}
	
	// TODO add workers that also call setstatus  /setversion on batch jobs and then pass them to send thread?
	// maybe we can generalise to setreply if needed, depending on reply format & batching of read queries
	// or do we just do this in the connection / reply sender thread(s)?
	
	return true;
}

// ««-------------- ≪ °◇◆◇° ≫ --------------»»

void ResultWorkers::ResultJobFail(void*& arg){
	
	// safety check in case the job somehow fails after returning its args to the pool
	if(arg==nullptr){
		return; // FIXME log this occurrence?
	}
	
	// FIXME hmm, well, i guess we say the query failed
	// - we had the results, but then lost them before sending
	
	ResultJobStruct* m_args=reinterpret_cast<ResultJobStruct*>(arg);
	++(*m_args->m_data->result_worker_job_fails);
	
	// return our job args to the pool
	m_args->m_pool.Add(m_args);
	m_args = nullptr;  // clear the local m_args variable... not strictly necessary
	arg = nullptr;     // clear the job 'data' member variable
	
}

void ResultWorkers::ResultJob(void*& arg){
	
	ResultJobStruct* m_args = reinterpret_cast<ResultJobStruct*>(arg);
	
	// for now each job processes a batch, not a set of batches
	//for(QueryBatch* batch : m_args->local_msg_queue){
		
		// read queries need to have their results interpreted,
		// write queries only need to have their insertion success status returned.
		// each batch should only contain messages that are either all read or all write.
		if(m_args->batch->queries.front().topic()[0]=='R'){
			
			// process batch of read queries
			
			for(ZmqQuery& query : m_args->batch->queries){
				
				// set whether the query succeeded or threw an exception
				query.setsuccess(uint32_t succeeded); // FIXME FILL
				
				// returned rows are sent back formatted as JSON, with each row a new zmq::message_t
				// resize zmq vector in preparation
				query.setresponserows(std::size(query.result));
				
				if(query.topic()[2]!=query_topic::generic){
					
					// standard queries generated by the libDAQInterface use `row_to_json`
					// to request results already packaged up into one JSON per row
					// so all we need to do is copy that into the zmq message
					for(size_t i=0; i<std::size(query.result); ++i){
						query.setresponse(i, query.result[i].c_str());
					}
					query.result.clear();
					
				} else {
					
					// FIXME if we can safely shoehorn in a wrapping call to `row_to_json`
					// around a user's generic sql, we can combine this with the above.
					// But, given the arbitrary complexity of statements, this may not be possible.
					// in which case, we need to loop over rows and convert them to JSON manually
					for(size_t i=0; i<std::size(query.result); ++i){
						
						// build a json from fields in this row
						m_args->tmpval = "{";
						for (pqxx::row::iterator it=query.result[i].begin(); it<query.result[i].end(); ++it){
							if(it!=query.result[i].begin()) m_args->tmpval += ", ";
							m_args->tmpval += "\"" + it->name() + "\":";
							// Field values are returned bare: i.e. '3' or 'cat' or '{"iam":"ajson"}'
							// but to convert this into JSON, strings need to be quoted:
							// i.e. { "field1":3, "field2":"cat", "field3":{"iam":"ajson"} }
							// this means we need to add enclosing quotes *only* for string fields
							if((it->type()==18) || (it->type()==25) || (it->type()==1042) || (it->type()==1043)){
								m_args->tmpval += "\""+it->c_str()+"\"";
							} else {
								m_args->tmpval += it->c_str();
							}
						}
						m_args->tmpval += "}";
						
						query.setresponse(i, m_args->tmpval);
						
					}
					query.result.clear();
					
				}
				
			} // loop over queries in this batch
			
		} else {
			
			// process batch of write queries
			// these are interleaved but results are grouped by type
			size_t devconfig_i = 0;
			size_t runconfig_i = 0;
			size_t calibration_i = 0;
			size_t plotlyplot_i = 0;
			size_t rootplot_i = 0;
			bool devconfigs_ok = !m_args->batch->devconfig_version_nums.empty();
			bool runconfigs_ok = !m_args->batch->runconfig_version_nums.empty();
			bool calibrations_ok = !m_args->batch->calibration_version_nums.empty();
			bool plotlyplots_ok = !m_args->batch->plotlyplot_version_nums.empty();
			bool rootplots_ok = !m_args->batch->rootplot_version_nums.empty();
			
			for(ZmqQuery& query : m_args->batch->queries){
				
				switch(query.topic()[2]){
					// alarms return just the success status
					case query_topic::alarm:
						query.setsuccess(m_args->batch->alarm_batch_success);
						query.setresponserows(0);
						break;
						
					// everything else returns a version number
					case query_topic::dev_config:
						query.setsuccess(devconfigs_ok);
						if(devconfigs_ok){
							query.setresponserows(1);
							query.setresponse(0, devconfig_version_nums[devconfig_i++]);
						}
						break;
						
					case query_topic::run_config:
						query.setsuccess(runconfigs_ok);
						if(runconfigs_ok){
							query.setresponserows(1);
							query.setresponse(0, runconfig_version_nums[runconfig_i++]);
						}
						break;
						
					case query_topic::calibration:
						query.setsuccess(calibrations_ok);
						if(calibrations_ok){
							query.setresponserows(1);
							query.setresponse(0, calibration_version_nums[calibration_i++]);
						}
						break;
						
					case query_topic::plotlyplot:
						query.setsuccess(plotlyplots_ok);
						if(plotlyplots_ok){
							query.setresponserows(1);
							query.setresponse(0, plotlyplot_version_nums[plotlyplot_i++]);
						}
						break;
						
					case query_topic::rootplot:
						query.setsuccess(rootplots_ok);
						if(rootplots_ok){
							query.setresponserows(1);
							query.setresponse(0, rootplot_version_nums[rootplot_i++]);
						}
						break;
						
					default:
						// FIXME corrupted topic, log it.
					
				}
				
			} // loop over queries in this batch
			
		} // if/else on whether this batch was read/write
		
//	} // loop over query batches
	
	// pass the batch onto the next stage of the pipeline for the DatabaseWorkers
	std::unique_lock<std::mutex> locker(m_args->m_data->query_replies_mtx);
	//m_args->m_data->query_replies.insert(m_args->m_data->query_replies.end(),
	//                                     m_args->local_msg_queue.begin(),m_args->local_msg_queue.end());
	m_args->m_data->query_replies.push_back(m_args->batch);
	locker.unlock();
	
	++(*m_args->m_data->result_worker_job_successes);
	
	// return our job args to the pool
	m_args->m_pool.Add(m_args);  // return our job args to the job args struct pool
	m_args = nullptr;  // clear the local m_args variable... not strictly necessary
	arg = nullptr;     // clear the job 'data' member variable
	
	return;
}


